version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform -y
  pre_build:
    commands:
      - terraform -chdir=terraform init
  build:
    commands:
      - terraform -chdir=terraform plan -out=tfplan
  post_build:
    commands:
      - terraform -chdir=terraform apply -auto-approve tfplan
